# Generated by Django 3.1.3 on 2021-04-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_closedlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedlisting',
            name='user',
        ),
    ]
