# Generated by Django 3.1.3 on 2021-04-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_closedlisting_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedListing',
        ),
    ]
