# Generated by Django 3.1.3 on 2021-04-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_closedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedlisting',
            name='auction_winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to='auctions.bid'),
        ),
    ]
