# Generated by Django 3.1.3 on 2021-04-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210414_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedListing',
        ),
    ]
